import type { SiteConfig } from "./site-config";

const C = {
  amber: "#F7B041", blue: "#0B86D1", teal: "#2EAD8E", coral: "#E06347",
  violet: "#905CCB", cyan: "#26C9D8",
};

export const semianalysisGenericConfig: SiteConfig = {
  mode: "generic",
  host: {
    name: "SemiAnalysis",
    shortName: "SemiAnalysis",
    logo: "/images/events/semianalysis.png",
    tagline: "The trusted voice in AI infrastructure — 200K+ subscribers, 3M+ monthly reach.",
  },
  // Generic: no fixed partner; the submitter tells us who they are via the form.
  partner: {
    name: "Your Brand",
    logo: "",
    color: C.blue,
  },
  year: "2026",
  tagColors: { NETWORKING: C.amber, BANQUET: C.blue, RESEARCH: C.violet, CONFERENCE: C.teal, PREMIUM: C.coral },
  events: [
    {
      name: "MLSys",
      dates: "May 18–22, 2026",
      location: "Bellevue, WA",
      tag: "NETWORKING",
      color: C.amber,
      status: "proposed",
      activation: "Happy Hour + Sponsorship",
      logo: "/images/events/mlsys.svg",
      monthIndex: 4, dayStart: 18, dayEnd: 22,
      about: "MLSys is the premier venue for research at the intersection of machine learning and systems. The engineers and researchers building the infrastructure ML runs on.",
      audience: "ML systems researchers, infrastructure engineers, hardware architects, and industry practitioners from companies building and deploying ML at scale.",
      ourPlan: "Host a curated happy hour for ~200 attendees targeting ML systems researchers and infrastructure engineers. Co-branded experience with the sponsor partner.",
      whyItMatters: "MLSys attendees decide what infrastructure to build on. High-signal, low-noise — every conversation is a potential pipeline conversion.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "6 weeks out", tasks: ["Confirm sponsorship tier and budget", "Align on branding and co-marketing assets", "Define target attendee profile", "Set KPIs"] },
        { phase: "Venue & Logistics", timing: "4 weeks out", tasks: ["Secure venue near convention center", "Book catering and beverage", "AV setup for welcome remarks", "Design co-branded signage"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Newsletter invite campaign (200K+ subs)", "Targeted outreach to MLSys registered attendees", "Social media promotion", "VIP invites to top 50 target attendees"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Venue setup + check-in", "Welcome remarks (5 min)", "Facilitated networking"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Attendee survey", "Attendee list for sales follow-up", "Content package", "ROI report"] },
      ],
    },
    {
      name: "Computex",
      dates: "Jun 2–5, 2026",
      location: "Taipei, Taiwan",
      tag: "BANQUET",
      color: C.blue,
      status: "proposed",
      activation: "VIP Banquet",
      logo: "/images/events/computex.svg",
      monthIndex: 5, dayStart: 2, dayEnd: 5,
      about: "The world's largest computing and technology trade show. Where TSMC, NVIDIA, AMD, Intel, and the entire semiconductor ecosystem converge.",
      audience: "Semiconductor executives, hardware engineers, supply chain leaders, OEMs, ODMs, and the global technology press. Heavy APAC hardware industry representation.",
      ourPlan: "Host a themed sit-down dinner for 300+ VIP attendees. Premium invitation-only event with curated seating and a sponsor keynote moment.",
      whyItMatters: "Computex is where hardware meets cloud. Association with a SemiAnalysis banquet positions your brand at the top of the APAC procurement conversation.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Finalize banquet theme", "Confirm keynote format", "Align on VIP invite list (C-suite)", "Budget finalization"] },
        { phase: "Creative & Production", timing: "6 weeks out", tasks: ["Design themed décor", "Plan seating chart", "Produce co-branded invitations", "Coordinate with venue"] },
        { phase: "Audience Building", timing: "4 weeks out", tasks: ["VIP invitation campaign", "Newsletter feature", "Cross-promotion with organizers", "RSVP and waitlist management"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production", "Red carpet welcome", "Seated dinner", "Sponsor keynote (15 min)", "Post-dinner networking"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Photo/video package", "Attendee follow-up", "Press coverage compilation", "ROI report"] },
      ],
    },
    {
      name: "ICML",
      dates: "Jul 6–11, 2026",
      location: "Seoul, South Korea",
      tag: "RESEARCH",
      color: C.violet,
      status: "proposed",
      activation: "Curated Research Event",
      logo: "/images/events/icml.svg",
      monthIndex: 6, dayStart: 6, dayEnd: 11,
      about: "One of the top three ML research conferences globally. The brightest minds in machine learning, from foundational research to applied ML.",
      audience: "ML researchers (academic + industry), PhD students, research lab directors, and applied ML engineers from DeepMind, FAIR, MSR, OpenAI, leading universities.",
      ourPlan: "A research-focused curated program adjacent to the main conference: speaker lineup, poster session, roundtable discussions. Premium research experience, not a sales pitch.",
      whyItMatters: "ICML attendees are the next generation of research leaders. Authentic engagement compounds for years.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "10 weeks out", tasks: ["Define research event format", "Identify speakers", "Align on themes", "Set target: 300 attendees"] },
        { phase: "Program Design", timing: "8 weeks out", tasks: ["Curate speaker lineup", "Design poster session format", "Plan roundtables", "Create event microsite"] },
        { phase: "Audience Building", timing: "5 weeks out", tasks: ["Targeted outreach to ICML attendees", "University lab partnerships", "Newsletter deep-dive", "Social campaign"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Venue setup with posters + AV", "Research talks (3-4 speakers)", "Poster session", "Roundtable discussions", "Closing reception"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Research recap on SemiAnalysis", "Speaker presentations shared", "Impact report", "Community engagement metrics"] },
      ],
    },
    {
      name: "Raise Paris",
      dates: "Jul 8–9, 2026",
      location: "Paris, France",
      tag: "NETWORKING",
      color: C.teal,
      status: "proposed",
      activation: "Happy Hours + Neo Cloud World",
      logo: "/images/events/raise.svg",
      monthIndex: 6, dayStart: 8, dayEnd: 9,
      about: "Europe's premier conference for the neo-cloud and AI infrastructure ecosystem. European cloud builders, sovereign cloud operators, AI startups, and infrastructure investors.",
      audience: "European cloud operators, sovereign cloud builders, AI startup founders, infrastructure investors, and policy-makers focused on digital sovereignty and AI compute in Europe.",
      ourPlan: "Multiple happy hour activations throughout Raise, co-produced with the organizing team. Strategic venues creating multiple touchpoints with the European AI community.",
      whyItMatters: "Europe's sovereign cloud and AI infrastructure market is booming. Raise is where European compute decisions get made.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Coordinate with Raise organizers", "Define happy hour schedule (2-3 events)", "Align on European messaging", "Budget for venue bookings"] },
        { phase: "Venue & Logistics", timing: "5 weeks out", tasks: ["Secure 2-3 Paris venues", "Coordinate catering", "Design co-branded materials", "Arrange photographer/videographer"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Cross-promotion with Raise communications", "Newsletter feature on European AI", "Targeted outreach to European AI startups", "VIP invites to sovereign cloud operators"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Setup at each venue", "Day 1: Opening night happy hour", "Day 2 afternoon: VIP networking (50 people)", "Day 2 evening: Closing happy hour"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["European market follow-up campaign", "Attendee insights report", "Content package", "Warm intros pipeline"] },
      ],
    },
    {
      name: "Yotta",
      dates: "Sep 28–30, 2026",
      location: "Las Vegas, NV",
      tag: "CONFERENCE",
      color: C.amber,
      status: "proposed",
      activation: "Conference Presence",
      logo: "/images/events/yotta.png",
      monthIndex: 8, dayStart: 28, dayEnd: 30,
      about: "The data center and infrastructure mega-conference in Las Vegas. The people who build, buy, and operate the physical infrastructure behind cloud and AI.",
      audience: "Data center operators, infrastructure buyers, facilities engineers, colocation providers, hyperscaler procurement teams, power/energy companies.",
      ourPlan: "Strategic conference presence with branded booth, speaking opportunities, hospitality suite, and 1:1 meetings with infrastructure buyers.",
      whyItMatters: "Data center infrastructure is the bottleneck for AI compute. Yotta attendees are the people solving it.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Secure speaking slot", "Define conference presence", "Identify target accounts", "Align messaging"] },
        { phase: "Logistics & Creative", timing: "5 weeks out", tasks: ["Design booth and materials", "Schedule 1:1 meetings", "Coordinate SemiAnalysis content", "Book hospitality suite"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Pre-conference outreach", "Newsletter feature", "Schedule top 20 meetings", "Social campaign"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Booth staffed with experts", "Private meetings", "Speaking session", "Evening networking reception"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Meeting follow-ups", "Lead pipeline report", "Insights brief", "Content recap"] },
      ],
    },
    {
      name: "OCP Global Summit",
      dates: "Oct 12–15, 2026",
      location: "San Jose, CA",
      tag: "CONFERENCE",
      color: C.blue,
      status: "proposed",
      activation: "Conference Presence",
      logo: "/images/events/ocp.jpg",
      monthIndex: 9, dayStart: 12, dayEnd: 15,
      about: "The Open Compute Project Global Summit. Founded by Facebook/Meta, OCP drives open-source hardware innovation for data centers.",
      audience: "Datacenter architects, hardware engineers, server and networking designers, procurement leaders from hyperscalers, open-source hardware community.",
      ourPlan: "Conference presence with speaking engagements, demo stations, and targeted meetings with hardware architects and procurement teams.",
      whyItMatters: "OCP is where open hardware standards get set. Credibility event for any sponsor with a technical story.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Secure speaking slot", "Plan demo stations", "Identify hardware architect targets", "Coordinate with OCP organizers"] },
        { phase: "Logistics & Creative", timing: "5 weeks out", tasks: ["Design demo station", "Prepare technical materials", "Schedule meetings", "Co-branded technical brief"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Technical preview content", "Outreach to OCP community", "Pre-schedule demos", "Social campaign"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Technical talk/panel", "Demo stations", "1:1 meetings", "Hosted dinner for top 30 architects"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Technical deep dive published", "Demo engagement metrics", "Follow-up with all visitors", "Community sentiment analysis"] },
      ],
    },
    {
      name: "SemiAnalysis Summit",
      dates: "October 2026",
      location: "TBA",
      tag: "PREMIUM",
      color: C.violet,
      status: "proposed",
      activation: "Flagship SemiAnalysis Event",
      logo: "/images/events/semianalysis.png",
      monthIndex: 9, dayStart: 15, dayEnd: 17,
      about: "The SemiAnalysis Summit is our flagship owned event — a curated gathering of the most senior operators, researchers, and executives in AI infrastructure. Invite-only, no expo floor, no noise.",
      audience: "CTOs, VP Engs, hyperscaler and frontier-lab leadership, sovereign cloud executives, and the investors funding the AI compute buildout. 300–400 decision-makers.",
      ourPlan: "Multi-day Summit combining curated talks, closed-door roundtables, and a premium evening experience. Presenting partner gets naming rights, keynote moment, and first look at the attendee list.",
      whyItMatters: "Our owned event. We control the invite list, programming, and narrative. The highest-leverage room of the year for mindshare with the AI infrastructure buying community.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "14 weeks out", tasks: ["Confirm presenting partner terms", "Align keynote and programming", "Set attendee targets (300-400, 70%+ Director+)", "Lock venue and budget"] },
        { phase: "Program Design", timing: "10 weeks out", tasks: ["Curate speaker lineup", "Design main stage + roundtables + evening", "Co-develop sponsor-led session", "Create event microsite"] },
        { phase: "Audience Building", timing: "8 weeks out", tasks: ["Invite-only campaign via SemiAnalysis CRM", "VIP outreach to top 150 targets", "Newsletter series building to Summit", "Coordinate cross-traffic with OCP week"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production", "Main stage with sponsor keynote slot", "Closed-door roundtables", "Evening networking experience"] },
        { phase: "Post-Event", timing: "2 weeks after", tasks: ["Mini-documentary", "Attendee list + sentiment report", "SemiAnalysis recap content series", "Pipeline report + renewal proposal"] },
      ],
    },
    {
      name: "COLM",
      dates: "Oct 6–9, 2026",
      location: "San Francisco, CA",
      tag: "PREMIUM",
      color: C.coral,
      status: "proposed",
      activation: "Boat Cruise",
      logo: "/images/events/colm.svg",
      monthIndex: 9, dayStart: 6, dayEnd: 9,
      about: "COLM (Conference on Language Modeling) is a focused conference dedicated entirely to language models. San Francisco is the epicenter of this work.",
      audience: "LLM researchers, foundation model engineers, AI startup founders, and the people building the most important technology of the decade.",
      ourPlan: "Premium boat cruise on SF Bay — our proven flagship format. An evening experience on the water with 200-300 LLM decision-makers.",
      whyItMatters: "COLM attendees are building the models that drive AI compute demand. Every major foundation model runs on cloud infrastructure.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "10 weeks out", tasks: ["Confirm boat cruise format", "Select vessel (250-300 capacity)", "Define experience flow", "Set guest list criteria"] },
        { phase: "Creative & Production", timing: "7 weeks out", tasks: ["Branded boarding experience", "Premium catering plan", "Curate entertainment", "Design commemorative gift"] },
        { phase: "Audience Building", timing: "4 weeks out", tasks: ["Exclusive invite campaign", "Newsletter anticipation feature", "Personal outreach to top 50", "Waitlist management"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Dockside setup", "Boarding with photographer", "Welcome toast", "Cruise route past Golden Gate + Alcatraz", "Premium dinner service", "Networking across decks"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Photo/video package with drone footage", "Sponsor follow-up materials", "Phased social media release", "ROI report"] },
      ],
    },
    {
      name: "NeurIPS",
      dates: "Dec 6–12, 2026",
      location: "Sydney, Australia",
      tag: "PREMIUM",
      color: C.coral,
      status: "proposed",
      activation: "Boat Cruise",
      logo: "/images/events/neurips.svg",
      monthIndex: 11, dayStart: 6, dayEnd: 12,
      about: "NeurIPS is the world's largest and most prestigious AI research conference. 15,000+ attendees. The 2026 edition in Sydney is the first time NeurIPS comes to Australia.",
      audience: "The entire AI ecosystem — researchers, engineers, executives, investors, policymakers, and press. Every major tech company, university, AI lab, and startup on the planet.",
      ourPlan: "The crown jewel — premium boat cruise on Sydney Harbour. Building on our 2025 format (750 attendees, 680 decision-makers with SAIL/ReadSail). Flagship presenting-partner opportunity.",
      whyItMatters: "NeurIPS is THE event. Presenting partner of the NeurIPS cruise is a statement that echoes through the entire AI community.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "12 weeks out", tasks: ["Define presenting partner scope", "Secure Sydney Harbour vessel (300+ capacity)", "Align on guest curation", "Set ambitious targets (400+)"] },
        { phase: "Creative & Production", timing: "8 weeks out", tasks: ["Flagship branded experience design", "Premium Australian catering", "Multi-deck experience plan", "Commission mini-documentary crew", "Limited-edition attendee gift"] },
        { phase: "Audience Building", timing: "6 weeks out", tasks: ["Exclusive invite campaign", "Leverage 2025 attendee list", "Newsletter series building to NeurIPS", "Coordinated social countdown", "Press outreach"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Harbour-side setup with red carpet", "Professional photographer at boarding", "Main deck keynote moment", "Multi-course dinner during cruise", "Skyline + Harbour Bridge views at dusk", "After-dinner networking with live music", "Gift bag farewell"] },
        { phase: "Post-Event", timing: "2 weeks after", tasks: ["Mini-documentary edit and release", "Professional photo gallery", "Attendee analytics + sentiment report", "Pipeline report", "Year-in-review recap", "Next-year renewal proposal"] },
      ],
    },
  ],
  stats: [
    { value: "3,100+", label: "Event Attendees in 2025", sub: "Across 8 major activations" },
    { value: "680", label: "Decision-Makers at NeurIPS", sub: "Our 2025 boat cruise with SAIL" },
    { value: "3M+", label: "Monthly Reach", sub: "Across newsletter, research, video, and social" },
    { value: "200K+", label: "Newsletter Subscribers", sub: "AI & semiconductor professionals" },
  ],
  pastEvents: [
    { name: "NeurIPS 2025 Boat Cruise", partner: "w/ SAIL (ReadSail)", attendees: "750", highlight: "680 decision-makers from Google, Meta, NVIDIA, Anthropic, and 40+ AI startups. 38% academia, 18% Big Tech, 12% AI startups." },
    { name: "Computex 2025 Banquet", partner: "AI Wonderland", attendees: "320+", highlight: "TSMC, AMD, Intel, MediaTek leadership in attendance. The must-attend event of the week in Taipei." },
    { name: "ICML 2025 Research Event", partner: "Research Community", attendees: "450+", highlight: "Top-cited ML researchers, keynote speakers attended. Standing room only." },
    { name: "Yotta 2025", partner: "Data Center Community", attendees: "3,000+", highlight: "3,000+ digital infrastructure leaders at MGM Grand. 200+ speakers, 150+ sponsors." },
  ],
  audienceBreakdown: [
    { label: "Academia & Research", pct: 38, color: C.violet },
    { label: "Big Tech (Google, Meta, etc.)", pct: 18, color: C.blue },
    { label: "AI Startups", pct: 12, color: C.amber },
    { label: "Frontier Labs", pct: 10, color: C.teal },
    { label: "Research Analysts", pct: 8, color: C.cyan },
    { label: "Investors", pct: 5, color: C.coral },
  ],
  whyUs: [
    { title: "200K+ Newsletter Subscribers", body: "The most-read independent publication covering semiconductors, AI infrastructure, and compute. The exact professionals your GTM team is trying to reach.", icon: "\u2709" },
    { title: "3M+ Monthly Reach", body: "Across newsletter, long-form research, video, and social — SemiAnalysis reaches 3M+ professionals every month. Engagement from the people who spec, architect, procure, and sign.", icon: "\u25B6" },
    { title: "Trusted Industry Voice", body: "Cited by Bloomberg, Financial Times, and The Information. When SemiAnalysis speaks, the semiconductor and AI community listens and acts.", icon: "\u2606" },
    { title: "750 at NeurIPS 2025", body: "Our boat cruise with SAIL drew 750 attendees and 680 decision-makers — 38% academia, 18% Big Tech, 12% AI startups. The format is proven.", icon: "\u2605" },
  ],
  // Testimonials hidden until real quotes are collected.
  testimonials: [],
  tiers: [
    { tier: "Tier 1", desc: "1 conference \u2014 $100K", features: ["Presenting partner at 1 chosen activation", "Co-branded presence, signage, and attendee experience", "Newsletter feature before and after the event", "Post-event attendee list + sentiment report"] },
    { tier: "Tier 2", desc: "2\u20133 conferences \u2014 $600K", features: ["Presenting partner at 2\u20133 activations of your choice", "Year-long co-marketing across SemiAnalysis channels", "Priority audience curation and VIP seating", "Quarterly strategy reviews with the SemiAnalysis team", "Cross-event attendee pipeline analysis"], highlight: true },
    { tier: "Tier 3", desc: "All conferences \u2014 pricing on request", features: ["Presenting partner across every activation on the calendar", "Full-season SemiAnalysis content integration (newsletter, video, research)", "Title-sponsor rights at flagship boat cruises (NeurIPS + COLM)", "Custom activation design + mini-documentary production", "Dedicated strategy + reporting team"] },
  ],
  hero: {
    eyebrow: "2026 Event Partnership",
    headline: "The Calendar Your\nBuyers Already Read",
    subtitle: "SemiAnalysis is the most-read independent voice in AI infrastructure — 200K+ subscribers, 3M+ monthly reach. We produce the events the decision-makers you're trying to sell actually show up to. Partner with us in 2026 and get your brand inside the rooms where the spend gets decided.",
  },
  whySection: {
    title: "Why SemiAnalysis?",
    lead: "We don't just reach the AI infrastructure community — we are the AI infrastructure community. Our audience isn't passive subscribers. They're the engineers, researchers, and executives who spec clusters, evaluate GPU clouds, and write the build-vs-buy memo. We earn their attention the hard way: with primary research, technical depth, and reporting that gets cited in earnings calls and engineering decisions. When you show up inside a SemiAnalysis activation, you're not renting attention — you're standing next to the most trusted independent voice in the category, in front of the exact people whose purchase decisions move your revenue.",
    groups: [
      { title: "Brand Positioning", items: ["Presenting partner branding at every activation", "Co-branded content across SemiAnalysis channels (200K+ subs, 3M+ monthly reach)", "Association with the most trusted voice in AI infrastructure", "Premium placement — not a logo wall, a real partnership"] },
      { title: "Audience Access", items: ["Direct access to 2,700+ decision-makers across 9 activations", "Curated introductions to target accounts at every activation", "Pre- and post-event attendee data for sales pipeline building", "78% Director+ seniority — the people who sign and decide"] },
      { title: "Content & Reach", items: ["Newsletter features to 200K+ subscribers", "3M+ total monthly reach across owned channels", "Event recap content and social media amplification", "Year-round brand presence beyond event days"] },
    ],
  },
  footer: "SemiAnalysis Events \u00A9 2026",
};
