import type { SiteConfig } from "./site-config";

const C = {
  amber: "#F7B041", blue: "#0B86D1", teal: "#2EAD8E", coral: "#E06347",
  violet: "#905CCB", cyan: "#26C9D8",
};

// Lambda brand accent — their signature deep purple
const LAMBDA_PURPLE = "#7C3AED";

export const semianalysisLambdaConfig: SiteConfig = {
  host: {
    name: "SemiAnalysis",
    shortName: "SemiAnalysis",
    logo: "/images/events/semianalysis.png",
    tagline: "The most-read independent publication covering semiconductors, AI infrastructure, and compute.",
  },
  partner: {
    name: "Lambda",
    logo: "/images/events/lambda.svg",
    color: LAMBDA_PURPLE,
  },
  year: "2026",
  tagColors: { NETWORKING: C.amber, BANQUET: C.blue, RESEARCH: C.violet, CONFERENCE: C.teal, PREMIUM: C.coral },
  events: [
    {
      name: "MLSys",
      dates: "May 18–22, 2026",
      location: "Bellevue, WA",
      tag: "NETWORKING",
      color: C.amber,
      status: "proposed",
      activation: "Happy Hour + Sponsorship",
      logo: "/images/events/mlsys.svg",
      monthIndex: 4, dayStart: 18, dayEnd: 22,
      about: "MLSys is the premier venue for research at the intersection of machine learning and systems. It brings together researchers and practitioners from ML, systems, hardware, and related fields to discuss cutting-edge work on the design, implementation, and deployment of ML systems.",
      audience: "ML systems researchers, infrastructure engineers, hardware architects, and industry practitioners from companies building and deploying ML at scale.",
      ourPlan: "Host an exclusive happy hour for ~200 attendees targeting ML systems researchers and infrastructure engineers. Sponsorship presence at the main conference with Lambda branding throughout. Focus on intimate networking — the kind of environment where real conversations happen between the people actually training and serving models in production.",
      whyItMatters: "MLSys attendees are Lambda's exact customer: the engineers and researchers who pick the cloud their team trains on. These are the people running 'where can I get H100s by Thursday' in their heads, and Lambda is the answer. High-signal, low-noise — every conversation is a potential pipeline.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "6 weeks out", tasks: ["Confirm sponsorship tier and budget allocation", "Align on branding guidelines and co-marketing assets", "Define target attendee profile and invite list criteria", "Set KPIs: target 200 attendees, 60%+ ML systems engineers"] },
        { phase: "Venue & Logistics", timing: "4 weeks out", tasks: ["Secure venue near convention center (rooftop bar or upscale lounge)", "Book catering — craft cocktails + elevated appetizers", "Arrange AV setup for brief welcome remarks", "Design and order co-branded signage, name badges, lanyards"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Launch invite campaign via SemiAnalysis newsletter (200K+ subscribers)", "Targeted outreach to MLSys registered attendees", "Social media promotion across SemiAnalysis channels", "Personal invites to top 50 target attendees from SemiAnalysis network"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Venue setup 3 hours prior — signage, check-in, AV test", "Check-in with QR codes for attendee tracking", "Welcome remarks from SemiAnalysis + Lambda representatives (5 min)", "Facilitated networking — no formal programming, organic conversations"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Attendee survey — engagement, satisfaction, follow-up interest", "Compile attendee list with company/role for Lambda sales follow-up", "Photo/video highlights package for social + internal reporting", "ROI report: attendance, seniority breakdown, follow-up pipeline"] },
      ],
    },
    {
      name: "Computex",
      dates: "Jun 2–5, 2026",
      location: "Taipei, Taiwan",
      tag: "BANQUET",
      color: C.blue,
      status: "proposed",
      activation: "AI Wonderland Banquet",
      logo: "/images/events/computex.svg",
      monthIndex: 5, dayStart: 2, dayEnd: 5,
      about: "Computex is the world's largest computing and technology trade show, held annually in Taipei. It's the beating heart of the global semiconductor and hardware supply chain — where TSMC, NVIDIA, AMD, Intel, and the entire ecosystem converge.",
      audience: "Semiconductor executives, hardware engineers, supply chain leaders, OEMs, ODMs, and the global technology press. Heavy representation from APAC-based hardware companies.",
      ourPlan: "Host the 'AI Wonderland' themed banquet — an exclusive sit-down dinner for 300+ VIP attendees. The venue is already booked. This will be a premium, invitation-only event with themed décor, curated seating arrangements to maximize high-value introductions, and a keynote moment spotlighting Lambda's GPU cloud and H100/H200 supply story for the APAC ML community.",
      whyItMatters: "Computex is where supply meets demand in GPU. Lambda's differentiated access to H100/H200/B200 supply is exactly the story the APAC hardware community wants to hear. Positioning Lambda as the cloud that can actually deliver the GPUs AI companies need — at this banquet, in front of the buyers who just spent the week negotiating hardware allocations — is uniquely potent.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Finalize banquet theme and Lambda integration points", "Confirm keynote speaker or fireside chat format", "Align on VIP invite list — target CTOs, VP Engs, and AI startup founders in APAC", "Budget finalization: venue, catering, production, travel"] },
        { phase: "Creative & Production", timing: "6 weeks out", tasks: ["Design 'AI Wonderland' themed décor and branded materials", "Plan seating chart for maximum networking value", "Produce co-branded invitations (digital + physical for top VIPs)", "Coordinate with Taipei venue on AV, staging, and flow"] },
        { phase: "Audience Building", timing: "4 weeks out", tasks: ["VIP invitation campaign — personal outreach to 500+ targets", "SemiAnalysis newsletter feature on Computex activation", "Coordinate with Computex organizers for cross-promotion", "Confirm RSVP list and manage waitlist"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production setup — themed décor, lighting, staging", "Red carpet / welcome experience with photographer", "Seated dinner with curated conversation starters at each table", "Keynote moment: 15-min spotlight on Lambda + SemiAnalysis vision for APAC AI compute", "Post-dinner networking lounge with cocktails"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Professional photo/video package for both teams", "Attendee follow-up emails with Lambda onboarding resources", "Press coverage compilation and social media highlights", "Full ROI report with attendee seniority analysis"] },
      ],
    },
    {
      name: "ICML",
      dates: "Jul 6–11, 2026",
      location: "Seoul, South Korea",
      tag: "RESEARCH",
      color: C.violet,
      status: "proposed",
      activation: "Special Research Event",
      logo: "/images/events/icml.svg",
      monthIndex: 6, dayStart: 6, dayEnd: 11,
      about: "The International Conference on Machine Learning (ICML) is one of the top three ML research conferences globally. It attracts the brightest minds in machine learning — from foundational research to applied ML. The 2026 edition in Seoul will draw significant APAC attendance.",
      audience: "ML researchers (academic and industry), PhD students, research lab directors, and applied ML engineers from Google DeepMind, Meta FAIR, Microsoft Research, OpenAI, and leading universities worldwide.",
      ourPlan: "A curated research event — poster session featuring Lambda-hosted research, intimate roundtables on scaling and efficiency, and a dinner for the top 80 researchers on-site. Lambda's research credit program gets a dedicated promotion moment. This is the event that converts academic users into Lambda power users.",
      whyItMatters: "ICML attendees are the next generation of frontier-lab founders and CTOs. These are the researchers who, in 18 months, will be spec'ing clusters for a new AI lab — and they'll remember which cloud spent time with them at ICML. Lambda's Research Credits program + authentic presence at ICML is the warmest possible pipeline into the 2027–2028 AI startup cohort.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "10 weeks out", tasks: ["Define research event format — workshop, symposium, or curated talks", "Identify Lambda research scientists + customer researchers for panel participation", "Align on research themes: efficient training, inference at scale, open-source models", "Set target: 300 attendees, 50%+ active ML researchers"] },
        { phase: "Program Design", timing: "8 weeks out", tasks: ["Curate speaker lineup — mix of Lambda customers, academia, and industry", "Design poster session format for Lambda-funded research", "Plan roundtable discussions on efficient training + inference", "Create event microsite with program details and speaker bios"] },
        { phase: "Audience Building", timing: "5 weeks out", tasks: ["Targeted outreach to ICML registered attendees", "Partner with university ML labs for student researcher attendance", "SemiAnalysis newsletter deep-dive on ICML research themes", "Social campaign featuring speaker previews and Lambda Research Credits program"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Venue setup — research poster displays, AV for talks, networking areas", "Curated research talks (3-4 speakers, 20 min each)", "Poster session and demo hour", "Roundtable discussions (4 tables, 15 people each, 45 min)", "Closing reception with open networking"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Publish research event recap on SemiAnalysis", "Share speaker presentations and discussion summaries", "Connect attendees with Lambda Research Credits onboarding", "Impact report: research community engagement metrics"] },
      ],
    },
    {
      name: "Raise Paris",
      dates: "Jul 8–9, 2026",
      location: "Paris, France",
      tag: "NETWORKING",
      color: C.teal,
      status: "proposed",
      activation: "Happy Hours + Neo Cloud World",
      logo: "/images/events/raise.svg",
      monthIndex: 6, dayStart: 8, dayEnd: 9,
      about: "Raise is Europe's premier conference for the neo-cloud and AI infrastructure ecosystem. It brings together European cloud builders, sovereign cloud operators, AI startups, and infrastructure investors. Paris in July is the nexus of European tech.",
      audience: "European cloud operators, sovereign cloud builders, AI startup founders, infrastructure investors, and policy-makers focused on digital sovereignty and AI compute in Europe.",
      ourPlan: "Multiple happy hour activations throughout Raise, co-produced with the organizing team. Lambda gets dedicated positioning as the GPU cloud category leader at the event where the European AI ecosystem converges. Happy hours at strategic venues around the conference, creating multiple touchpoints with European AI founders and researchers.",
      whyItMatters: "European AI startups are growing fast and need GPU capacity that isn't locked to a hyperscaler contract. Lambda's neutral, flexible, performance-first position is exactly what this audience is looking for. Raise is where European compute decisions get made in 2026 — Lambda should be in the middle of every one of those conversations.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Coordinate with Raise organizing committee on event integration", "Define happy hour schedule — 2-3 events across 2 days", "Align on European market messaging for Lambda", "Budget for multiple venue bookings in central Paris"] },
        { phase: "Venue & Logistics", timing: "5 weeks out", tasks: ["Secure 2-3 venues near Raise conference (historic Parisian locations)", "Coordinate catering — French-inspired menus with local partners", "Design co-branded materials with European market focus", "Arrange photographer/videographer for all events"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Cross-promote with Raise official communications", "SemiAnalysis newsletter feature on European AI infrastructure", "Targeted outreach to European AI startup founders and CTOs", "VIP invites to sovereign cloud operators and EU policy leaders"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Setup at each venue — branding, check-in, welcome signage", "Day 1 evening: Opening night happy hour (broader audience)", "Day 2 afternoon: Intimate VIP networking for Lambda priority accounts (invite-only, 50 people)", "Day 2 evening: Closing celebration happy hour"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["European market follow-up campaign for Lambda", "Attendee insights report: European GPU buying signals", "Content package: photos, testimonials, social highlights", "Warm introductions pipeline for Lambda European sales team"] },
      ],
    },
    {
      name: "Yotta",
      dates: "Sep 28–30, 2026",
      location: "Las Vegas, NV",
      tag: "CONFERENCE",
      color: C.amber,
      status: "proposed",
      activation: "Conference Presence",
      logo: "/images/events/yotta.png",
      monthIndex: 8, dayStart: 28, dayEnd: 30,
      about: "Yotta is the data center and infrastructure mega-conference in Las Vegas. It brings together the people who build, buy, and operate the physical infrastructure behind cloud and AI — from power and cooling to networking and compute.",
      audience: "Data center operators, infrastructure buyers, facilities engineers, colocation providers, hyperscaler procurement teams, and power/energy companies entering the AI infrastructure space.",
      ourPlan: "Targeted conference presence focused on Lambda's physical footprint story — dedicated GPU capacity across owned and leased facilities. Speaking slot on GPU cloud infrastructure economics, hospitality suite for private conversations with colocation and power partners, and curated meetings with infrastructure buyers evaluating GPU-as-a-service.",
      whyItMatters: "Yotta is where Lambda's supply chain story lands. The people in this room are negotiating the power, space, and capacity that GPU clouds run on. Lambda's partnerships with colocation providers and ability to scale capacity faster than hyperscalers is a differentiator the Yotta audience appreciates and amplifies.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Secure speaking slot or panel participation for Lambda leader", "Define conference presence: booth, signage, meeting rooms", "Identify target accounts for scheduled meetings (colocation, power partners)", "Align messaging: Lambda capacity story"] },
        { phase: "Logistics & Creative", timing: "5 weeks out", tasks: ["Design booth and branded materials", "Schedule 1:1 meetings with target infrastructure partners", "Coordinate SemiAnalysis content for conference distribution", "Book hospitality suite for private conversations"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Pre-conference outreach to registered attendees", "SemiAnalysis newsletter feature on GPU cloud infrastructure", "Schedule specific meetings with top 20 target accounts", "Social media campaign building momentum for conference presence"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Booth staffed with Lambda infrastructure team", "Hosted meetings and demos in private meeting rooms", "Speaking session or panel participation", "Evening networking reception for top contacts"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Meeting notes and follow-up action items for all 1:1s", "Partner pipeline report for Lambda infrastructure team", "Conference insights brief: GPU infrastructure market trends", "Content recap for SemiAnalysis audience"] },
      ],
    },
    {
      name: "OCP Global Summit",
      dates: "Oct 12–15, 2026",
      location: "San Jose, CA",
      tag: "CONFERENCE",
      color: C.blue,
      status: "proposed",
      activation: "Conference Presence",
      logo: "/images/events/ocp.jpg",
      monthIndex: 9, dayStart: 12, dayEnd: 15,
      about: "The Open Compute Project Global Summit is the hardware community's flagship event. Founded by Facebook/Meta, OCP drives open-source hardware innovation for data centers. It's where the next generation of server, storage, and networking hardware gets designed and decided.",
      audience: "Datacenter architects, hardware engineers, server and networking designers, procurement leaders from hyperscalers, and the open-source hardware community. Heavy representation from Meta, Microsoft, Google, and major ODMs.",
      ourPlan: "Lambda presence at OCP focused on the open-hardware angle — Lambda's transparent approach to cluster design, benchmarks, and interconnect choices resonates with the OCP community. Demo stations, a technical deep-dive session, and a hosted dinner for the top 30 hardware architects co-located with the SemiAnalysis Summit week.",
      whyItMatters: "OCP is where hardware standards are set — and where the people designing the next generation of GPU servers and networking work. Lambda's differentiated cluster design and openness about architecture choices is exactly the kind of story this community wants to hear from a cloud provider. This is a credibility event for Lambda's technical brand.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Secure speaking slot on Lambda cluster architecture or benchmarks", "Plan demo stations for H100/H200 cluster performance", "Identify hardware architect targets for meetings", "Coordinate with OCP organizers on session placement"] },
        { phase: "Logistics & Creative", timing: "5 weeks out", tasks: ["Design demo station with live Lambda cluster benchmarks", "Prepare technical deep-dive materials for hardware audience", "Schedule meetings with datacenter architects and procurement", "Co-branded SemiAnalysis technical brief on Lambda infrastructure"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Technical preview content on SemiAnalysis channels", "Targeted outreach to OCP community members", "Pre-schedule demos with priority attendees", "Social campaign featuring Lambda's cluster innovations"] },
        { phase: "Event Execution", timing: "Days of", tasks: ["Technical talk/panel on Lambda infrastructure", "Demo stations running throughout conference", "Scheduled 1:1 meetings with hardware decision-makers", "Hosted dinner for top 30 hardware architects (evening of Day 2, tied to Summit week)"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Technical content published on SemiAnalysis (deep dive)", "Demo engagement metrics and meeting pipeline report", "Follow-up with all demo visitors and meeting attendees", "Hardware community sentiment analysis"] },
      ],
    },
    {
      name: "SemiAnalysis Summit",
      dates: "October 2026",
      location: "TBA",
      tag: "PREMIUM",
      color: C.violet,
      status: "proposed",
      activation: "Flagship SemiAnalysis Event",
      logo: "/images/events/semianalysis.png",
      monthIndex: 9, dayStart: 15, dayEnd: 17,
      about: "The SemiAnalysis Summit is our flagship owned event — a curated gathering of the most senior operators, researchers, and executives in AI infrastructure. Invite-only, no expo floor, no noise. The single moment each year when the entire SemiAnalysis community convenes in one room.",
      audience: "CTOs, VP Engs, hyperscaler and frontier-lab leadership, sovereign cloud executives, and the investors funding the AI compute buildout. The 300–400 people whose decisions set the direction of the industry.",
      ourPlan: "A multi-day Summit combining curated talks, closed-door roundtables, and a premium evening experience. Lambda as presenting partner gets named-sponsor rights, a keynote moment on the state of GPU cloud, and first look at the attendee list. Because this is our owned event, sponsor integration goes deeper than any third-party conference allows — including a Lambda-curated roundtable on inference economics.",
      whyItMatters: "Owned events outperform sponsored ones because we control the invite list, the programming, and the narrative. For Lambda specifically: this is the single highest-leverage room of the year for GPU cloud mindshare. 300–400 AI infrastructure decision-makers, all reachable by Lambda afterward through SemiAnalysis's warm channel, associated with the brand that writes the definitive analysis on the category.",
      internalNote: "Tie to OCP and SemiAnalysis internal offsite — leverage overlapping travel week and co-locate execution. Do not surface publicly.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "14 weeks out", tasks: ["Confirm Lambda as presenting partner + co-naming rights", "Align keynote speaker and programming integration", "Set attendee targets: 300–400, 70%+ Director+", "Lock venue and production budget"] },
        { phase: "Program Design", timing: "10 weeks out", tasks: ["Curate speaker lineup across SemiAnalysis + Lambda + external voices", "Design Day 1 main stage + Day 2 roundtables + evening experience", "Co-develop Lambda-led session on inference economics / GPU cloud outlook", "Create event microsite and invite page"] },
        { phase: "Audience Building", timing: "8 weeks out", tasks: ["Launch invite-only campaign via SemiAnalysis CRM", "VIP outreach to top 150 target attendees", "Newsletter series building to Summit", "Coordinate with OCP week cross-traffic"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production + branded experience", "Main stage programming with Lambda keynote slot", "Closed-door roundtables (capped at 15 per room)", "Evening networking experience with press opportunity"] },
        { phase: "Post-Event", timing: "2 weeks after", tasks: ["Professional photo/video + mini-documentary", "Attendee list + sentiment report delivered to Lambda", "SemiAnalysis recap content series", "Pipeline + ROI report + 2027 renewal proposal"] },
      ],
    },
    {
      name: "COLM",
      dates: "Oct 6–9, 2026",
      location: "San Francisco, CA",
      tag: "PREMIUM",
      color: C.coral,
      status: "proposed",
      activation: "Boat Cruise",
      logo: "/images/events/colm.svg",
      monthIndex: 9, dayStart: 6, dayEnd: 9,
      about: "COLM (Conference on Language Modeling) is a newer, focused conference dedicated entirely to language models — the technology behind ChatGPT, Claude, Gemini, and the entire LLM revolution. San Francisco is the epicenter of this work.",
      audience: "LLM researchers, foundation model engineers, AI startup founders, and the people building the most important technology of the decade. Extremely high concentration of decision-makers from frontier AI labs.",
      ourPlan: "Premium boat cruise on the San Francisco Bay — our proven flagship format. An evening experience on the water with 200-300 of the most important people in language modeling. Lambda as presenting partner, with subtle branding throughout the experience and a fireside chat on what frontier labs need from their GPU cloud.",
      whyItMatters: "Every LLM researcher and foundation model engineer in the room is currently making a decision: train on a hyperscaler lock-in contract, or use flexible GPU capacity from a neutral provider like Lambda. The COLM cruise puts Lambda in front of that decision at exactly the right moment, in an environment designed for real conversation rather than sales pitches.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "10 weeks out", tasks: ["Confirm boat cruise format and Lambda co-branding approach", "Select vessel — capacity 250-300, premium finish", "Define experience flow: boarding, cruise, program, docking", "Set guest list criteria: LLM researchers, AI founders, infrastructure leads"] },
        { phase: "Creative & Production", timing: "7 weeks out", tasks: ["Design branded boarding experience and on-deck signage", "Plan catering menu — premium seated dinner + open bar", "Curate entertainment: live DJ or jazz ensemble on deck", "Design commemorative item (branded gift for attendees)", "Coordinate sunset timing for optimal experience"] },
        { phase: "Audience Building", timing: "4 weeks out", tasks: ["Exclusive invite campaign — 'You've been selected' messaging", "SemiAnalysis newsletter feature building anticipation", "Personal outreach to top 50 AI researchers and founders", "Waitlist management to maintain exclusivity"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Dockside setup: red carpet, branded check-in, welcome drinks", "Boarding experience with photographer", "Welcome toast from SemiAnalysis + Lambda on deck", "Cruise route: under Golden Gate Bridge, around Alcatraz, Bay views", "Premium dinner service during cruise", "Open networking on multiple decks post-dinner"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Professional photo/video package (drone footage of cruise)", "Attendee follow-up with Lambda onboarding materials", "Social media content release (phased over 2 weeks)", "Full ROI report: attendee quality, conversations initiated, pipeline"] },
      ],
    },
    {
      name: "NeurIPS",
      dates: "Dec 6–12, 2026",
      location: "Sydney, Australia",
      tag: "PREMIUM",
      color: C.coral,
      status: "proposed",
      activation: "Boat Cruise",
      logo: "/images/events/neurips.svg",
      monthIndex: 11, dayStart: 6, dayEnd: 12,
      about: "NeurIPS (Conference on Neural Information Processing Systems) is the world's largest and most prestigious AI research conference. With 15,000+ attendees, it's where the global AI community converges. The 2026 edition in Sydney marks the first time NeurIPS comes to Australia — a massive moment for APAC AI.",
      audience: "The entire AI ecosystem — researchers, engineers, executives, investors, policymakers, and press. NeurIPS draws from every major tech company, university, AI lab, and startup on the planet.",
      ourPlan: "The crown jewel of our activation calendar — a premium boat cruise on Sydney Harbour. Building on our proven NeurIPS format (partnered with SAIL/ReadSail in 2025, 750 attendees, 680 decision-makers), this will be the must-attend event of the conference. Flagship experience with Lambda as presenting partner, capacity for 300+ on a premium vessel with views of the Sydney Opera House and Harbour Bridge, and Lambda's Research Credits program featured as the exclusive partner offering for the APAC research community.",
      whyItMatters: "NeurIPS is THE event for AI research. Our 2025 cruise with SAIL proved the format: 750 attendees, 680 decision-makers, 38% academia, 18% Big Tech, 12% AI startups. For Lambda, this is a once-a-year opportunity to be the name associated with the most coveted evening of the most important AI conference on the planet — and to put Lambda Research Credits in the hands of every rising researcher in APAC.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "12 weeks out", tasks: ["Define Lambda as 'Presenting Partner' — top-tier branding", "Secure premium vessel in Sydney Harbour (300+ capacity)", "Align on guest curation strategy based on 2025 learnings", "Set ambitious targets: 400 attendees, expand beyond 2025 results"] },
        { phase: "Creative & Production", timing: "8 weeks out", tasks: ["Design flagship branded experience — from invite to follow-up", "Premium catering with Australian coastal theme", "Plan multi-deck experience: dinner deck, networking deck, views deck", "Commission professional event film crew (mini-documentary)", "Design limited-edition attendee gift co-branded with Lambda"] },
        { phase: "Audience Building", timing: "6 weeks out", tasks: ["Launch exclusive invitation campaign (NeurIPS registration required)", "Leverage 2025 attendee list for return invites", "SemiAnalysis newsletter series building to NeurIPS", "Coordinated social campaign with countdown content featuring Lambda Research Credits", "Press outreach for pre-event coverage"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Harbour-side setup: branded tent, red carpet, welcome drinks", "Premium boarding experience with professional photographer", "Keynote moment on main deck — Lambda + SemiAnalysis vision for AI compute", "Multi-course dinner during cruise through Sydney Harbour", "Views of Sydney skyline and Harbour Bridge at dusk", "After-dinner networking party with live music", "Docking and farewell with gift bags"] },
        { phase: "Post-Event", timing: "2 weeks after", tasks: ["Mini-documentary edit and release", "Professional photo gallery for both teams", "Comprehensive attendee analytics and sentiment report", "Pipeline report: connections made, follow-ups initiated, Research Credits activated", "Year-in-review recap: all 9 activations, cumulative impact", "2027 partnership renewal proposal"] },
      ],
    },
  ],
  stats: [
    { value: "3,100+", label: "Event Attendees in 2025", sub: "Across 8 major activations" },
    { value: "680", label: "Decision-Makers at NeurIPS", sub: "Our 2025 boat cruise with SAIL" },
    { value: "3M+", label: "Monthly Reach", sub: "Across newsletter, research, video, and social" },
    { value: "200K+", label: "Newsletter Subscribers", sub: "AI & semiconductor professionals" },
  ],
  pastEvents: [
    { name: "NeurIPS 2025 Boat Cruise", partner: "w/ SAIL (ReadSail)", attendees: "750", highlight: "680 decision-makers from Google, Meta, NVIDIA, Anthropic, and 40+ AI startups. 38% academia, 18% Big Tech, 12% AI startups." },
    { name: "Computex 2025 Banquet", partner: "AI Wonderland", attendees: "320+", highlight: "TSMC, AMD, Intel, MediaTek leadership in attendance. The must-attend event of the week in Taipei." },
    { name: "ICML 2025 Research Event", partner: "Research Community", attendees: "450+", highlight: "Top-cited ML researchers, keynote speakers attended. Standing room only." },
    { name: "Yotta 2025", partner: "Data Center Community", attendees: "3,000+", highlight: "3,000+ digital infrastructure leaders at MGM Grand. 200+ speakers, 150+ sponsors." },
  ],
  audienceBreakdown: [
    { label: "Academia & Research", pct: 38, color: C.violet },
    { label: "Big Tech (Google, Meta, etc.)", pct: 18, color: C.blue },
    { label: "AI Startups", pct: 12, color: C.amber },
    { label: "Frontier Labs", pct: 10, color: C.teal },
    { label: "Research Analysts", pct: 8, color: C.cyan },
    { label: "Investors", pct: 5, color: C.coral },
  ],
  whyUs: [
    { title: "200K+ Newsletter Subscribers", body: "The most-read independent publication covering semiconductors, AI infrastructure, and compute. 200,000+ AI and semiconductor industry professionals, researchers, investors, and enthusiasts — including the ML engineers and researchers Lambda competes to reach.", icon: "\u2709" },
    { title: "3M+ Monthly Reach", body: "Across newsletter, long-form research, video, and social — SemiAnalysis reaches 3M+ professionals every month. Not impressions. Engagement from the people who spec clusters, procure capacity, and choose their GPU cloud.", icon: "\u25B6" },
    { title: "Trusted Industry Voice", body: "Cited by Bloomberg, Financial Times, and The Information. SemiAnalysis's deep-dive analysis on GPU cloud economics, inference cost curves, and capacity shortages reaches the exact buyers Lambda is trying to convert.", icon: "\u2606" },
    { title: "750 at NeurIPS 2025", body: "Our boat cruise with SAIL drew 750 attendees and 680 decision-makers — 38% academia, 18% Big Tech, 12% AI startups. These are Lambda's next 500 customers.", icon: "\u2605" },
  ],
  // Testimonials hidden until real quotes are collected.
  testimonials: [],
  tiers: [
    { tier: "Tier 1", desc: "1 conference \u2014 $100K", features: ["Presenting partner at 1 chosen activation", "Co-branded presence, signage, and attendee experience", "Newsletter feature before and after the event", "Post-event attendee list + Lambda Research Credits distribution"] },
    { tier: "Tier 2", desc: "2\u20133 conferences \u2014 $600K", features: ["Presenting partner at 2\u20133 activations of your choice", "Year-long co-marketing across SemiAnalysis channels", "Priority audience curation and VIP seating", "Quarterly strategy reviews with the SemiAnalysis team", "Cross-event attendee pipeline analysis for Lambda"], highlight: true },
    { tier: "Tier 3", desc: "All conferences \u2014 pricing on request", features: ["Presenting partner across every activation on the calendar", "Full-season SemiAnalysis content integration (newsletter, research, video)", "Title-sponsor rights at flagship boat cruises (NeurIPS + COLM)", "Custom activation design + mini-documentary production", "Dedicated strategy + reporting team", "Lambda Research Credits campaign integrated across all events"] },
  ],
  hero: {
    eyebrow: "2026 Event Partnership",
    headline: "Meet the AI Builders\nWho Choose Their Cloud",
    subtitle: "A strategic marketing partnership between SemiAnalysis and Lambda — putting Lambda in front of the researchers, engineers, and founders who decide where the next generation of models gets trained.",
  },
  whySection: {
    title: "Why SemiAnalysis?",
    lead: "We don't just reach the AI infrastructure community — we are the AI infrastructure community. Our audience isn't passive subscribers. They're the engineers, researchers, and executives who spec clusters, evaluate GPU clouds, and write the build-vs-buy memo. We earn their attention the hard way: with primary research, technical depth, and reporting that gets cited in earnings calls and engineering decisions. When Lambda shows up inside a SemiAnalysis activation, you're not renting attention — you're standing next to the most trusted independent voice in the category, in front of the exact researchers and ML engineers who turn into Lambda customers the moment they have a workload. Every event is a room we curated, on a calendar we built, with a brand that builders already read daily. That's what makes this partnership compound — not just a logo impression, but an endorsement from the source your customers already trust.",
    groups: [
      { title: "Brand Positioning", items: ["Presenting partner branding at every activation", "Co-branded content across SemiAnalysis channels (200K+ subscribers, 3M+ monthly reach)", "Association with the most trusted voice in AI infrastructure", "Premium placement — not a logo wall, a real partnership"] },
      { title: "Audience Access", items: ["Direct access to 2,700+ decision-makers across 9 activations", "Curated introductions to target accounts at every activation", "Pre- and post-event attendee data for Lambda sales pipeline", "78% Director+ seniority — the people who sign and decide"] },
      { title: "Content & Reach", items: ["Newsletter features to 200K+ subscribers", "3M+ total monthly reach across owned channels", "Event recap content and social media amplification", "Year-round Lambda brand presence beyond event days"] },
    ],
  },
  footer: "SemiAnalysis \u00D7 Lambda \u00A9 2026 \u2014 Confidential",
};
