import type { SiteConfig } from "./site-config";

const C = {
  amber: "#F7B041", blue: "#0B86D1", teal: "#2EAD8E", coral: "#E06347",
  violet: "#905CCB", cyan: "#26C9D8",
};

export const templateConfig: SiteConfig = {
  host: {
    name: "Your Agency",
    shortName: "Agency",
    logo: "/images/events/semianalysis.png",
    tagline: "The trusted voice in your industry — where decision-makers read, watch, and convene.",
  },
  partner: {
    name: "Brand",
    logo: "/images/events/aws.svg",
    color: "#FF9900",
  },
  year: "2026",
  tagColors: { NETWORKING: C.amber, BANQUET: C.blue, RESEARCH: C.violet, CONFERENCE: C.teal, PREMIUM: C.coral },
  events: [
    {
      name: "Industry Summit",
      dates: "Mar 10–12, 2026",
      location: "Austin, TX",
      tag: "NETWORKING",
      color: C.amber,
      status: "proposed",
      activation: "VIP Happy Hour",
      logo: "/images/events/semianalysis.png",
      monthIndex: 2, dayStart: 10, dayEnd: 12,
      about: "A premier industry gathering for leaders and builders. Attendees skew senior, decisions get made, and the best conversations happen off the main agenda.",
      audience: "Senior practitioners, founders, operators, and investors who shape the direction of the industry.",
      ourPlan: "Host a curated happy hour for 150–200 attendees adjacent to the main conference. Co-branded experience with premium catering, intimate venue, and light programming. The goal is introductions that lead to pipeline.",
      whyItMatters: "This audience builds what comes next. A co-branded activation here positions you as the partner of choice for the community that matters.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "6 weeks out", tasks: ["Confirm sponsorship tier and budget", "Align on branding and co-marketing assets", "Define target attendee profile and invite criteria", "Set success metrics and KPIs"] },
        { phase: "Venue & Logistics", timing: "4 weeks out", tasks: ["Secure venue near conference center", "Book catering and beverage program", "Arrange AV for welcome remarks", "Design branded signage and collateral"] },
        { phase: "Audience Building", timing: "3 weeks out", tasks: ["Launch invite campaign via host channels", "Targeted outreach to registered attendees", "Social media promotion", "Personal invites to top 50 target guests"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["On-site setup and check-in", "Welcome remarks from both brands (5 min)", "Facilitated networking", "Photography and documentation"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Attendee survey and feedback", "Share attendee list with partner", "Highlight content package", "ROI and pipeline report"] },
      ],
    },
    {
      name: "Global Trade Show",
      dates: "Apr 14–17, 2026",
      location: "Singapore",
      tag: "BANQUET",
      color: C.blue,
      status: "proposed",
      activation: "VIP Dinner",
      logo: "/images/events/semianalysis.png",
      monthIndex: 3, dayStart: 14, dayEnd: 17,
      about: "A global industry trade show drawing 30,000+ attendees from every major company in the ecosystem. APAC's most important week of the year.",
      audience: "Executives, procurement leaders, product managers, and the international press. Heavy C-suite representation.",
      ourPlan: "Host an exclusive invitation-only dinner for 250–300 VIPs. Themed experience with curated seating, keynote moment, and post-dinner networking.",
      whyItMatters: "A single evening where every executive decision-maker is in one room. Association with a signature event carries all year.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "8 weeks out", tasks: ["Finalize theme and partner integration points", "Confirm keynote format and speakers", "Align on VIP invite list — target C-suite", "Budget finalization"] },
        { phase: "Creative & Production", timing: "6 weeks out", tasks: ["Design themed décor and co-branded materials", "Plan seating chart for max networking value", "Produce physical and digital invitations", "Coordinate with venue on AV and flow"] },
        { phase: "Audience Building", timing: "4 weeks out", tasks: ["VIP invitation campaign (500+ targeted invites)", "Newsletter feature across host channels", "Cross-promotion with event organizers", "RSVP and waitlist management"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production setup", "Red carpet / welcome experience", "Seated dinner with curated tables", "Keynote moment and networking lounge"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Professional photo/video package", "Attendee follow-up sequence", "Press coverage compilation", "Full ROI and pipeline report"] },
      ],
    },
    {
      name: "Research Symposium",
      dates: "Jun 2–5, 2026",
      location: "Boston, MA",
      tag: "RESEARCH",
      color: C.violet,
      status: "proposed",
      activation: "Curated Program",
      logo: "/images/events/semianalysis.png",
      monthIndex: 5, dayStart: 2, dayEnd: 5,
      about: "A top-tier research conference where the next generation of ideas gets presented and debated. Highly credible, highly attended by technical leadership.",
      audience: "Researchers (academic and industry), PhD students, research directors, and the applied teams turning research into product.",
      ourPlan: "Co-host a half-day research program adjacent to the main conference — curated talks, poster session, and roundtable discussions. Premium research experience, not a sales event.",
      whyItMatters: "Researchers at this event become the leaders of tomorrow. Authentic engagement with this community pays dividends for years.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "10 weeks out", tasks: ["Define research program format", "Identify speakers and panelists from partner team", "Align on research themes", "Set attendance and engagement targets"] },
        { phase: "Program Design", timing: "8 weeks out", tasks: ["Curate speaker lineup", "Design poster session format", "Plan roundtable discussions", "Create event microsite"] },
        { phase: "Audience Building", timing: "5 weeks out", tasks: ["Targeted outreach to registered attendees", "Partner with university research labs", "Deep-dive newsletter feature", "Social campaign featuring speakers"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Venue setup for talks and posters", "Curated research talks (3–4 speakers)", "Poster session and demo hour", "Roundtable discussions and closing reception"] },
        { phase: "Post-Event", timing: "1 week after", tasks: ["Publish research recap", "Share speaker decks and summaries", "Connect attendees with partner programs", "Community engagement report"] },
      ],
    },
    {
      name: "Flagship Gala",
      dates: "Oct 20–23, 2026",
      location: "New York, NY",
      tag: "PREMIUM",
      color: C.coral,
      status: "proposed",
      activation: "Premium Experience",
      logo: "/images/events/semianalysis.png",
      monthIndex: 9, dayStart: 20, dayEnd: 23,
      about: "The marquee event of the year — 15,000+ attendees, global press coverage, and every major company in the category represented.",
      audience: "The entire industry — executives, investors, operators, press, and the rising stars building what's next.",
      ourPlan: "A premium flagship experience for 300+ on the evening of Day 2 — venue with a view, professional production, keynote moment, and a mini-documentary capturing the evening.",
      whyItMatters: "This is THE event. Association with the best activation here is a statement that echoes through the industry for the rest of the year.",
      activationSteps: [
        { phase: "Partnership Alignment", timing: "12 weeks out", tasks: ["Define 'Presenting Partner' branding and scope", "Secure premium venue (300+ capacity)", "Align on guest curation strategy", "Set attendance targets"] },
        { phase: "Creative & Production", timing: "8 weeks out", tasks: ["Design flagship branded experience end-to-end", "Premium catering and beverage program", "Plan multi-zone experience", "Commission professional film crew", "Design attendee gift"] },
        { phase: "Audience Building", timing: "6 weeks out", tasks: ["Launch exclusive invite campaign", "Leverage prior attendee lists", "Newsletter countdown series", "Coordinated social campaign", "Press outreach"] },
        { phase: "Event Execution", timing: "Day of", tasks: ["Full venue production", "Red carpet arrival experience", "Keynote moment on main stage", "Multi-course dinner", "After-party with live entertainment", "Attendee gift bags"] },
        { phase: "Post-Event", timing: "2 weeks after", tasks: ["Mini-documentary edit and release", "Professional photo gallery", "Attendee sentiment report", "Pipeline report", "Year-in-review recap", "Renewal proposal for next year"] },
      ],
    },
  ],
  stats: [
    { value: "2,500+", label: "Event Attendees in 2025", sub: "Across 4 major activations" },
    { value: "400", label: "Decision-Makers at Flagship", sub: "Our 2025 premium experience" },
    { value: "8", label: "Countries Represented", sub: "Global reach, local impact" },
    { value: "150K+", label: "Newsletter Subscribers", sub: "Industry professionals and builders" },
  ],
  pastEvents: [
    { name: "2025 Flagship Gala", partner: "Premium Experience", attendees: "400", highlight: "Over 300 decision-makers from the top 50 companies in the category. Executive keynote attendance, standing room only." },
    { name: "2025 Global Trade Show Dinner", partner: "VIP Banquet", attendees: "280+", highlight: "C-suite leadership from across the industry. Covered by 3 major outlets." },
    { name: "2025 Research Symposium", partner: "Research Program", attendees: "350+", highlight: "Leading researchers and applied teams. Rated one of the best side events of the week." },
    { name: "2025 Industry Summit", partner: "Happy Hour", attendees: "200+", highlight: "Intimate networking that produced 40+ qualified partner introductions." },
  ],
  audienceBreakdown: [
    { label: "Senior Operators", pct: 32, color: C.violet },
    { label: "Executives (VP+)", pct: 24, color: C.blue },
    { label: "Founders & CEOs", pct: 16, color: C.amber },
    { label: "Investors", pct: 12, color: C.teal },
    { label: "Researchers", pct: 10, color: C.cyan },
    { label: "Press & Analysts", pct: 6, color: C.coral },
  ],
  whyUs: [
    { title: "150K+ Newsletter Subscribers", body: "A trusted industry voice read by the professionals who build, buy, and invest in the category. High engagement, not passive distribution.", icon: "\u2709" },
    { title: "Consistent Content Reach", body: "Deep technical and strategic content that decision-makers actively seek out. Every piece lands with people who spec, architect, and sign.", icon: "\u25B6" },
    { title: "Trusted Industry Voice", body: "Cited by major business and technical press. When we speak, the community listens and acts.", icon: "\u2606" },
    { title: "Proven Event Format", body: "Our flagship activations consistently draw 300+ decision-makers. The format is tested, the audience is real, the results are measurable.", icon: "\u2605" },
  ],
  testimonials: [
    { quote: "The single best networking event I attended all year. Every conversation was high-signal.", author: "VP of Operations", company: "Growth-Stage Company" },
    { quote: "Unlike typical conference happy hours, every person I talked to was senior and relevant. That never happens.", author: "Director of Strategy", company: "Fortune 500" },
    { quote: "I made three partnerships at this event that turned into signed contracts within 90 days.", author: "CEO", company: "Category Leader" },
    { quote: "These events feel exclusive without being exclusionary. The curation is what makes the difference.", author: "Research Lead", company: "Top Research Lab" },
  ],
  tiers: [
    { tier: "Select", desc: "Choose 2 events", features: ["Co-branded presence at selected events", "Newsletter features around event dates", "Attendee data and post-event reporting", "Dedicated touchpoint at each activation"] },
    { tier: "Premier", desc: "Full season access", features: ["Presenting partner at all activations", "Year-round content integration", "Priority audience curation at every event", "Quarterly strategy sessions and reporting", "Custom activation design for flagships"], highlight: true },
    { tier: "Flagship", desc: "Anchor 1 marquee event", features: ["Title sponsor of the flagship gala", "Maximum brand presence at the biggest moment", "VIP guest curation and seating", "Full event recap documentary"] },
  ],
  hero: {
    eyebrow: "2026 Event Partnership",
    headline: "Partner Where\nYour Audience Already Gathers",
    subtitle: "A strategic marketing partnership that puts your brand in front of the decision-makers who matter — at the events they already prioritize.",
  },
  whySection: {
    title: "Why Partner With Us?",
    lead: "We don't just reach the industry — we are the industry. Our audience isn't passive subscribers. They're the operators, executives, and builders defining what's next.",
    groups: [
      { title: "Brand Positioning", items: ["Presenting partner branding at every activation", "Co-branded content across our channels", "Association with a trusted industry voice", "Premium placement — not a logo wall, a real partnership"] },
      { title: "Audience Access", items: ["Direct access to decision-makers across every event", "Curated introductions to target accounts", "Pre- and post-event attendee data for pipeline building", "High seniority — the people who sign and decide"] },
      { title: "Content & Reach", items: ["Newsletter features to an engaged subscriber base", "Video and written content integration", "Event recap content and social amplification", "Year-round brand presence beyond event days"] },
    ],
  },
  footer: "Template \u00A9 2026 — Preview",
};
